AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: RoadWarrior Backend API
Resources:
    RoadWarriorBackendFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: main
            CodeUri: main.zip
            Runtime: go1.x
            MemorySize: 128
            Policies: AWSLambdaBasicExecutionRole
            Timeout: 10
            Events:
                GetResource:
                    Type: Api
                    Properties:
                        Path: /api/{proxy+}
                        Method: any

Outputs:
    RoadWarriorBackendAPI:
        Description: URL for application
        Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
        Export:
            Name: RoadWarriorBackendAPI
